FROM docker.io/node:20.19-bullseye-slim
RUN apt-get update && apt-get install -y dos2unix

COPY docker-scripts/build-front.sh /usr/local/bin/build-project.sh

RUN dos2unix /usr/local/bin/build-project.sh && chmod +x /usr/local/bin/build-project.sh
