FROM docker.io/bitnami/node:20.19.2

RUN apt update && apt install -y dos2unix

COPY docker-scripts/build-data-access-layer.sh /usr/local/bin/build-project.sh

RUN dos2unix /usr/local/bin/build-project.sh && chmod +x /usr/local/bin/build-project.sh